[package]
name = "metatui"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.30.0-alpha.2" }
crossterm = "0.29.0"
chrono = "0.4.40"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
